import { useUser, UserButton, Protect } from "@clerk/nextjs";
import Link from "next/link";
import { useRouter } from "next/router";
import type { ReactNode } from "react";
import PageTransition from "./PageTransition";
import { AlexFinLogo } from "@/components/brand/AlexFinLogo";
import { ThemeToggle } from "@/components/ThemeToggle";
import { BRAND_NAME } from "@/lib/brand";

interface LayoutProps {
  children: ReactNode;
}

const linkBase =
  "text-sm font-medium text-[var(--text-secondary)] transition-colors duration-200 hover:text-[var(--text-primary)]";
const linkActive = "text-sm font-medium text-[var(--accent)]";

export default function Layout({ children }: LayoutProps) {
  const { user } = useUser();
  const router = useRouter();
  const isActive = (path: string) => router.pathname === path;

  const navLink = (path: string, label: string) => (
    <Link href={path} className={isActive(path) ? linkActive : linkBase}>
      {label}
    </Link>
  );

  return (
    <Protect
      fallback={
        <div className="flex min-h-screen items-center justify-center bg-[var(--bg)]">
          <p className="text-sm text-[var(--text-secondary)]">Redirecting to sign in…</p>
        </div>
      }
    >
      <div className="flex min-h-screen flex-col bg-[var(--bg)]">
        <nav className="sticky top-0 z-20 border-b border-[var(--border)] bg-[var(--surface)]/95 backdrop-blur-md">
          <div className="mx-auto max-w-[1200px] px-6">
            <div className="flex h-16 items-center justify-between">
              <div className="flex items-center gap-8">
                <Link
                  href="/"
                  className="flex items-center gap-2"
                  aria-label={BRAND_NAME}
                >
                  <AlexFinLogo variant="horizontal" className="h-7 w-auto" />
                </Link>
                <div className="hidden items-center gap-6 md:flex">
                  {navLink("/dashboard", "Dashboard")}
                  {navLink("/accounts", "Accounts")}
                  {navLink("/advisor-team", "Advisor team")}
                  {navLink("/analysis", "Analysis")}
                  {navLink("/settings", "Settings")}
                </div>
              </div>
              <div className="flex items-center gap-2 sm:gap-3">
                <ThemeToggle />
                <span className="hidden max-w-[200px] truncate text-sm text-[var(--text-secondary)] sm:inline">
                  {user?.firstName || user?.emailAddresses[0]?.emailAddress}
                </span>
                <UserButton afterSignOutUrl="/" />
              </div>
            </div>
            <div className="flex flex-wrap items-center gap-x-4 gap-y-2 pb-3 md:hidden">
              {navLink("/dashboard", "Dashboard")}
              {navLink("/accounts", "Accounts")}
              {navLink("/advisor-team", "Advisor team")}
              {navLink("/analysis", "Analysis")}
              {navLink("/settings", "Settings")}
            </div>
          </div>
        </nav>

        <main className="flex-1">
          <PageTransition>{children}</PageTransition>
        </main>

        <footer className="mt-auto border-t border-[var(--border)] bg-[var(--surface)]">
          <div className="mx-auto max-w-[1200px] px-6 py-8">
            <p className="text-center text-xs leading-relaxed text-[var(--text-secondary)]">
              Outputs are generated by software and large language models; they are
              not reviewed by a licensed financial advisor and are not investment
              advice. For informational purposes only.
            </p>
            <p className="mt-4 text-center text-xs text-[var(--text-secondary)] opacity-80">
              © {new Date().getFullYear()} {BRAND_NAME}
            </p>
          </div>
        </footer>
      </div>
    </Protect>
  );
}
