import { useUser, UserButton, Protect } from "@clerk/nextjs";
import Link from "next/link";
import { useRouter } from "next/router";
import type { ReactNode } from "react";
import PageTransition from "./PageTransition";
import { AlexFinLogo } from "@/components/brand/AlexFinLogo";
import { ThemeToggle } from "@/components/ThemeToggle";
import { BRAND_NAME } from "@/lib/brand";

interface LayoutProps {
  children: ReactNode;
}

const linkBase =
  "text-sm font-medium text-[var(--text-secondary)] transition-colors duration-200 hover:text-[var(--text-primary)]";
const linkActive = "text-sm font-medium text-[var(--accent)]";

export default function Layout({ children }: LayoutProps) {
  const { user } = useUser();
  const router = useRouter();
  const isActive = (path: string) => router.pathname === path;

  const navLink = (path: string, label: string) => (
    <Link href={path} className={isActive(path) ? linkActive : linkBase}>
      {label}
    </Link>
  );

  return (
    <Protect
      fallback={
        <div className="flex min-h-screen items-center justify-center bg-[var(--bg)]">
          <p className="text-sm text-[var(--text-secondary)]">Redirecting to sign in…</p>
        </div>
      }
    >
      <div className="flex min-h-screen flex-col bg-[var(--bg)]">
        <nav className="sticky top-0 z-20 border-b border-[var(--border)] bg-[var(--surface)]/95 backdrop-blur-md">
          <div className="app-container">
            <div
              className="grid min-w-0 grid-cols-[1fr_auto_1fr] items-center gap-[var(--space-4)]"
              style={{ minHeight: "var(--header-height)" }}
            >
              <div className="flex min-w-0 items-center justify-start">
                <Link href="/" className="flex shrink-0 items-center gap-2" aria-label={BRAND_NAME}>
                  <AlexFinLogo variant="horizontal" className="h-7 w-auto" />
                </Link>
              </div>
              <nav className="hidden min-w-0 items-center justify-center gap-[var(--space-6)] overflow-x-auto md:flex">
                {navLink("/dashboard", "Portfolio")}
                {navLink("/dashboard#holdings", "Holdings")}
                {navLink("/advisor-team", "Advisor team")}
                {navLink("/analysis", "Analysis")}
                {navLink("/settings", "Settings")}
              </nav>
              <div className="flex min-w-0 items-center justify-end gap-[var(--space-2)] sm:gap-[var(--space-3)]">
                <ThemeToggle />
                <span className="hidden max-w-[200px] truncate text-sm text-[var(--text-secondary)] lg:inline">
                  {user?.firstName || user?.emailAddresses[0]?.emailAddress}
                </span>
                <UserButton afterSignOutUrl="/" />
              </div>
            </div>
            <div className="flex flex-wrap items-center gap-x-[var(--space-4)] gap-y-[var(--space-2)] pb-[var(--space-3)] md:hidden">
              {navLink("/dashboard", "Portfolio")}
              {navLink("/dashboard#holdings", "Holdings")}
              {navLink("/advisor-team", "Advisor team")}
              {navLink("/analysis", "Analysis")}
              {navLink("/settings", "Settings")}
            </div>
          </div>
        </nav>

        <main className="min-w-0 flex-1 overflow-x-hidden">
          <PageTransition>
            <div className="app-container min-w-0">{children}</div>
          </PageTransition>
        </main>

        <footer className="mt-auto border-t border-[var(--border)] bg-[var(--surface)]">
          <div className="app-container py-[var(--space-8)]">
            <p className="text-center text-xs leading-relaxed text-[var(--text-secondary)]">
              Outputs are generated by software and large language models; they are not reviewed by a
              licensed financial advisor and are not investment advice. For informational purposes only.
            </p>
            <p className="mt-[var(--space-4)] text-center text-xs text-[var(--text-secondary)] opacity-80">
              © {new Date().getFullYear()} {BRAND_NAME}
            </p>
          </div>
        </footer>
      </div>
    </Protect>
  );
}
