import {
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import LandingHero from "../components/landing/Hero";
import ProductSnapshot from "../components/landing/ProductSnapshot";
import ValuePropositions from "../components/landing/ValuePropositions";
import HowItWorks from "../components/landing/HowItWorks";
import SystemTransparency from "../components/landing/SystemTransparency";
import FinalCTA from "../components/landing/FinalCTA";
import { AlexFinLogo } from "@/components/brand/AlexFinLogo";
import { ThemeToggle } from "@/components/ThemeToggle";
import { BRAND_NAME, PRODUCT_SUBTITLE, pageTitle } from "@/lib/brand";

export default function Home() {
  return (
    <>
      <Head>
        <title>{pageTitle("AI Financial Intelligence Platform")}</title>
        <meta name="description" content={PRODUCT_SUBTITLE} />
      </Head>
      <div className="min-h-screen bg-[var(--bg)] text-[var(--text-primary)]">
        <header className="sticky top-0 z-20 border-b border-[var(--border)] bg-[var(--surface)]/95 backdrop-blur-md">
          <div className="mx-auto flex max-w-[1200px] items-center justify-between px-6 py-3.5">
            <Link href="/" className="flex items-center" aria-label={BRAND_NAME}>
              <AlexFinLogo variant="horizontal" className="h-7 w-auto" />
            </Link>
            <nav className="flex items-center gap-2 sm:gap-3">
              <ThemeToggle />
              <SignedOut>
                <SignInButton mode="modal">
                  <button
                    type="button"
                    className="rounded-lg px-3 py-2 text-sm font-medium text-[var(--text-secondary)] transition hover:bg-[var(--card)] sm:px-4"
                  >
                    Sign in
                  </button>
                </SignInButton>
                <SignUpButton mode="modal">
                  <button
                    type="button"
                    className="rounded-lg bg-[var(--accent)] px-3 py-2 text-sm font-medium text-white transition duration-200 hover:opacity-95 sm:px-4"
                  >
                    Get started
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <Link
                  href="/dashboard"
                  className="rounded-lg px-3 py-2 text-sm font-medium text-[var(--text-secondary)] transition hover:bg-[var(--card)] sm:px-4"
                >
                  View dashboard
                </Link>
                <UserButton afterSignOutUrl="/" />
              </SignedIn>
            </nav>
          </div>
        </header>

        <main>
          <LandingHero />
          <ProductSnapshot />
          <ValuePropositions />
          <HowItWorks />
          <SystemTransparency />
          <FinalCTA />
        </main>

        <footer className="border-t border-[var(--border)] bg-[var(--surface)] py-10 text-center text-xs leading-relaxed text-[var(--text-secondary)]">
          <p className="mx-auto max-w-[720px] px-6">
            Outputs are generated by software and large language models; they are
            not reviewed by a licensed financial advisor and are not investment
            advice. For informational purposes only.
          </p>
          <p className="mt-4 opacity-80">
            © {new Date().getFullYear()} {BRAND_NAME}
          </p>
        </footer>
      </div>
    </>
  );
}
